alias csedi="openvpn-gui.exe --command silent_connection 1 && openvpn-gui.exe --command connect DESWS-0009"
alias dsedi="openvpn-gui.exe --command disconnect DESWS-0009"

PROJECTX_FOLDERS="~/git ~/git/helpany"
PROJECTX_INTERNET_CHECKS=1
PROJECTX_GIT_FETCH=1
PROJECTX_BUMP_PYTHON=0

# Helpany
# Lightest Blue: #28d2e6
# Lightest Pink: #ff788c
# Text Blue: #000787
HELPANY_LIGHT_BLUE="#28d2e6"
HELPANY_LIGHT_PINK="#ff788c"
HOST_INDICATOR_COLOR=$HELPANY_LIGHT_BLUE
HOST_EMOJI="🚀"
# HOST_USER_SUFFIX="🩵🩷"
# HOST_USER_SUFFIX="\U1FA75\U1FA77"
HOST_USER_SUFFIX="💙💗"

SPACESHIP_HOST_SHOW="false"
SPACESHIP_VENV_SYMBOL="🪨 "
SPACESHIP_GIT_BRANCH_COLOR=$HELPANY_LIGHT_PINK
SPACESHIP_GIT_STATUS_COLOR=$HELPANY_LIGHT_BLUE

TMUX_PANE_SEPERATOR_COLOR=$HELPANY_LIGHT_PINK

# Sedimentum Legacy
# SEDIMENTUM_MAGENTA="#732f37"
# HOST_INDICATOR_COLOR=$MAGENTA
# HOST_EMOJI="🚀"
# HOST_USER_SUFFIX="🦄🪨"
# SPACESHIP_HOST_SHOW="false"
# SPACESHIP_VENV_SYMBOL="🌍 "
