PROJECTX_FOLDERS="~/git ~/git/jaywalker"
PROJECTX_INTERNET_CHECKS=0
PROJECTX_GIT_FETCH=1
PROJECTX_BUMP_PYTHON=0

JAYWALKER_BLUE="#3b487c"
JAYWALKER_WHITE="#ffffff"
HOST_INDICATOR_COLOR=$JAYWALKER_BLUE
HOST_EMOJI="🚥"
HOST_USER_SUFFIX="🚶🚗"

SPACESHIP_HOST_SHOW="false"
SPACESHIP_VENV_SYMBOL="⚓ "
SPACESHIP_GIT_BRANCH_COLOR=$JAYWALKER_WHITE
SPACESHIP_GIT_STATUS_COLOR=$JAYWALKER_BLUE

TMUX_PANE_SEPERATOR_COLOR=$JAYWALKER_BLUE
