PROJECTX_FOLDERS="~/git"
PROJECTX_INTERNET_CHECKS=0
PROJECTX_GIT_FETCH=1
PROJECTX_BUMP_PYTHON=0

PILATUS_BLUE="#0f43bb"
PILATUS_WHITE="#ffffff"
HOST_INDICATOR_COLOR=$PILATUS_BLUE
HOST_EMOJI="🛩️ "
HOST_USER_SUFFIX="🗻🛫"

SPACESHIP_HOST_SHOW="false"
SPACESHIP_VENV_SYMBOL="🔧 "
SPACESHIP_GIT_BRANCH_COLOR=$PILATUS_WHITE
SPACESHIP_GIT_STATUS_COLOR=$PILATUS_BLUE

TMUX_PANE_SEPERATOR_COLOR=$PILATUS_BLUE
export WSL_DISTRO_NAME="Ubuntu"
